### PR TITLE
add ASmap for run 1730210400

### PR DESCRIPTION
**Pull request by jurraca**
This adds the asmap.dat result for the coordinated launch from https://github.com/asmap/asmap-data/issues/18 from epoch 1730210400. We had a match from 4 out of 5 participants in the coordinated launch.

To confirm the result of the encoding you can use [asmap-tool](https://github.com/bitcoin/bitcoin/tree/master/contrib/asmap).
```
$ shasum -a 256 1730210400_final_result.txt
8986e7baf0aea86b6b63766968d77edb384d1c332b23725596e18693235419ce  1730210400_final_result.txt

$ python3 contrib/asmap/asmap-tool.py encode 1730210400_final_result.txt 1730210400_asmap.dat

$ shasum -a 256 1730210400_asmap.dat
93afd5c0a82f82fca9988881f397739427c9c34bc1adb337e0d00978dcd1863a 1730210400_asmap.dat
```

### CODE REVIEW

**Comment by 0xB10C** [comment]
ACK acfd979e2115a24bf2c533bbc42db7694f65eea2

Encoding my `final_results.txt` I too get an asmap.dat file with the hash `93afd5c0a82f82fca9988881f397739427c9c34bc1adb337e0d00978dcd1863a`. I checked that the file added here hashes to the `93afd5c0..` hash.

**Comment by 0xB10C** [comment]
I thought about making latest_asmap.dat a symlink of an asmap file. I think it should work for Linux an probably macOS too. However, it might not work for Windows.

**Comment by jurraca** [comment]
> However, it might not work for Windows.

yea let me see if I get a windows user to test this.

**Comment by jurraca** [comment]
> However, it might not work for Windows.

Windows does not seem to resolve the symlink natively. There's some configuration to change ( enable Windows Developer mode) and maybe set `git config core.symlinks true` as well, but not sure. I'd like the opinion of someone who knows Windows better to confirm this. Is there a Core windows testing person?

**Comment by fjahr** [comment]
@0xB10C @jurraca The latest_asmap file exists primarily so we have a constant link to the latest file on GitHub for download that can be shared/documented like in the seeds readme: https://github.com/bitcoin/bitcoin/tree/master/contrib/seeds I tested this initially but [GitHub doesn't follow symlinks](https://github.com/dear-github/dear-github/issues/156) so even if it would work on windows we still couldn't make it a symlink. Maybe there are more elegant ways to do this and I am happy to consider new idea but I don't want to add any additional dependency and this is simple and works for now.

**Comment by 0xB10C** [comment]
fwiw: I now run one of my monitoring nodes with `-asmap=latest_asmap.dat` (being 1730210400)

**Comment by fjahr** [comment]
> fwiw: I now run one of my monitoring nodes with `-asmap=latest_asmap.dat` (being 1730210400)

Awesome! Please let us know if you see anything noteworthy, it will definitely be interesting for the embedding discussion in core.

**Pull request merged**
