### PR TITLE
Add ASmap from run 1733234400

### PR DESCRIPTION
**Pull request by jurraca**
This adds the asmap.dat result for the coordinated launch from https://github.com/asmap/asmap-data/issues/20 from the epoch 1733234400.. We had a match from 4/4 participants in the coordinated launch.

To confirm the result of the encoding you can use [asmap-tool](https://github.com/bitcoin/bitcoin/tree/master/contrib/asmap).

```
$ shasum -a 256 1733234400.txt
af69975d8325db35d43c4b91883893e78c1d9c562c774439c474215d501c0e2b  1733234400_asmap.dat

$ python3 contrib/asmap/asmap-tool.py encode 1733234400_final_result.txt 1733234400_asmap.dat

$ shasum -a 256 1733234400_asmap.dat
1c417dad13a0b22fbb171c639d3f4badb879891db3a5de22176fda38b8d83ed9  1733234400_asmap.dat
```

(nb: I thought about removing the oldest one, but I think it makes sense to keep the last 6 files, assuming we do one run per month which we've only approximately done so far. )

### CODE REVIEW

**Comment by fjahr** [comment]
Seems there is an empty commit at db17d86d52c41dda91f37a044b86bfc8d8829b66, not sure how that happened?

> I thought about removing the oldest one, but I think it makes sense to keep the last 6 files, assuming we do one run per month which we've only approximately done so far.

Yeah, IMO we don't need to remove old ones in the foreseeable future unless Github restricts the amount of data saved here. It would be interesting to look at these older maps and see how they evolved in a year or so. I guess they will still be available in the history but it wouldn't bother me if there are 20 or 30 files here in master either.

**Comment by jurraca** [comment]
> Seems there is an empty commit at https://github.com/asmap/asmap-data/commit/db17d86d52c41dda91f37a044b86bfc8d8829b66, not sure how that happened?

i was getting a merge conflict on the binary file and couldn't it unless I did a merge commit. idk either I've never run into this before. Was thinking we squash the commits when we merge, unless you know the solution w/o merge commit.

**Comment by fjahr** [comment]
Hm, not sure how git handles this but maybe that happens if you copy to override the file. When I did it lately I explicitly removed the latest file first and then copied the new file to the latest file name, that still works without conflict for me. Pushed a branch here: https://github.com/asmap/asmap-data/commits/pr21/ Let me know if it doesn't work like this, then maybe it's a git or system issue.

**Comment by jurraca** [comment]
thanks, fixed.

**Comment by fjahr** [comment]
ACK, I got the same result hash: `1c417dad13a0b22fbb171c639d3f4badb879891db3a5de22176fda38b8d83ed9`

**Pull request merged**
